config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "forecasts#index"

  resources :forecasts, only: [ :index ] do
    collection do
      get :forecast
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
  end

  def forecast
    params.expect([ :postal_code, :street_address, :city, :state ])

    street_address = params[:street_address]
    city = params[:city]
    state = params[:state]
    postal_code = params[:postal_code]

    # Build an array of the address params so it can be easily formatted in both a machine-readable format and a
    # human-readable format
    address_array = [ street_address, city, state, postal_code ]
    api_address = address_array.join(",").strip

    # Since there's no object needed to hold the forecast data, we can use the postal code as a cache key instead of
    # using Model#cache_key
    cache_key = "weather_#{postal_code}"

    # Build up the variables to be used in the rendered view
    @address = address_array.join(", ").strip

    # Check to see if the object is already cached
    @cached = Rails.cache.exist?(cache_key)

    # Use the geocoding service object to get the latitude and longitude of the address, then use the weather service
    # object to get the forecast data. Cache the geocoding and forecast data for 30 minutes.
    @forecast = Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
      coordinates = ::Geocoding::Google.call(address: api_address)

      # If the geocoding service returns a failure, return the error message
      if coordinates.is_a?(::Geocoding::Failure)
        coordinates.to_h
      else
        ::Weather::WeatherGov.call(latitude: coordinates.latitude, longitude: coordinates.longitude).to_h
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/forecast.html.erb
<div>
  <h1 class="font-bold text-4xl mb-8">Forecast</h1>
  <% if @forecast[:error].present? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
      <strong class="font-bold">Error:</strong>
      <span class="block sm:inline"><%= @forecast[:error] %></span>
    </div>
  <% else %>
    <div class="mb-4">Address: <%= @address %></div>
    <div class="mb-4">Temperature: <%= @forecast[:temperature].round(2) %> °F</div>
    <div class="mb-4">Wind speed: <%= @forecast[:wind_speed].round(2) %> mph</div>
    <div class="mb-4">Cached: <%= @cached ? 'True' : 'False' %></div>
  <% end %>

  <%= link_to "Get another forecast", forecasts_path, class: 'text-blue-500 hover:text-blue-800' %>
</div>

app/views/forecasts/index.html.erb
<div>
  <h1 class="font-bold text-4xl mb-8">Weather forecast</h1>
  <address class="w-full min-w-sm max-w-md">
    <%= form_with url: forecast_forecasts_path, method: :get, local: true, data: { turbo: false },  class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", autocomplete: "on" do |form| %>
      <div class="mb-4">
        <%= form.label :street_address, "Street address", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :street_address, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Street address", autocomplete: "street-address", required: true %>
      </div>

      <div class="mb-4">
        <%= form.label :city, "City", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :city, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "City", autocomplete: "address-level2", required: true %>
      </div>

      <div class="mb-4">
        <%= form.label :state, "State", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :state, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "State", autocomplete: "address-level1", required: true %>
      </div>

      <div class="mb-6">
        <%= form.label :postal_code, "Postal code", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :postal_code, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Postal code", autocomplete: "postal-code", required: true %>
      </div>

      <%= form.submit "Get forecast", class: "bg-blue-500 text-white p-2 rounded w-full" %>
    <% end %>
  </address>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>